<a href="https://colab.research.google.com/github/CoderCouple/pytorch_tutorial_1/blob/main/ch00_pytorch_basic_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Basics of PyTorch**
Torch tensors: https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


In [ ]:
!nvidia-smi

Fri Feb 20 21:55:45 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          Off |   00000000:04:00.0 Off |                    0 |
| N/A   33C    P0             71W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [ ]:
scalar = torch.tensor(5)
scalar

tensor(5)

In [ ]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [ ]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
scalar.ndim

0

In [ ]:
vector.ndim

1

In [ ]:
matrix.ndim

2

In [ ]:
tensor.ndim

3

#**Random Tensors**

###Why random tensors ?
###Random tensors are important because

Start with random tensors  -> look at data -> update random numbers -> look at data -> update again -> Keep repeating this till the final epoch


Random tensors : https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
random_scalar = torch.rand(4)
random_scalar

tensor([0.7245, 0.3674, 0.8198, 0.5603])

In [ ]:
random_matrix = torch.rand(2,3)
random_matrix

tensor([[0.7866, 0.5249, 0.5319],
        [0.5320, 0.2536, 0.1554]])

In [ ]:
random_tensor = torch.rand(1,3,4)
random_tensor


tensor([[[0.7410, 0.7299, 0.6870, 0.0497],
         [0.1939, 0.3143, 0.2605, 0.1707],
         [0.9422, 0.9429, 0.5631, 0.9150]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# create a random tensor for image
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#**Tensor of ZERO'S and ONE'S**
ones: https://docs.pytorch.org/docs/stable/generated/torch.ones.html

zeros: https://docs.pytorch.org/docs/stable/generated/torch.zeros.html

In [ ]:
ones = torch.ones(size= (2,3))
ones


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
zeros = torch.ones(size=(2,2,3))
zeros

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
zeros.dtype

torch.float32

#**Creating a range of tensors and tensor like**

arange: https://docs.pytorch.org/docs/stable/generated/torch.arange.html

tensor_like: https://docs.pytorch.org/docs/stable/generated/torch.zeros_like.html

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_thousand = torch.arange(start=0, end=1001, step=100)
one_to_thousand

tensor([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
one_to_ten_like = torch.zeros_like(one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#**Tensor Data Type**

**Note: ** This is going to be one of the 3 most common errors
1. Tesors with inccorect data type
2. Tesors with inccorect shape
3. Tesors with inccorect device

In [ ]:
float_32_tensor = torch.tensor([3.0,5.0,2.0], device= None, dtype=torch.float32, requires_grad= False )
float_32_tensor

tensor([3., 5., 2.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 5., 2.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 25.,  4.])

#**Tensor Attributes**
1. shape
2. device
3. dtype

In [ ]:
# find out the attributes of the tensor
print(f"Datatype of tensor: {float_32_tensor.dtype}")
print(f"Shape of tensor: {float_32_tensor.shape}")
print(f"Device of tensor: {float_32_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3])
Device of tensor: cpu
