<a href="https://colab.research.google.com/github/CoderCouple/pytorch_tutorial_1/blob/main/ch01_pytorch_basic_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# **Tensor Operations**
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication
6. Transpose

In [2]:
tensor_a = torch.tensor([1,2,3])
tensor_a


tensor([1, 2, 3])

In [3]:
tensor_b = torch.tensor([4,5,6])
tensor_b

tensor([4, 5, 6])

In [7]:
# Addition Operator
tensor_add = tensor_a + tensor_b
tensor_add

tensor([5, 7, 9])

In [8]:
# Addition Function
tensor_add = torch.add(tensor_a, tensor_b)
tensor_add

tensor([5, 7, 9])

In [9]:
#Subtraction Operator
tensor_sub = tensor_a - tensor_b
tensor_sub

tensor([-3, -3, -3])

In [10]:
#Subtraction Function
tensor_sub = torch.sub(tensor_a, tensor_b)
tensor_sub

tensor([-3, -3, -3])

In [24]:
%%time
# Tensor Multiplication (Element wise)
tensor_mul = tensor_a * tensor_b
tensor_mul

CPU times: user 169 µs, sys: 15 µs, total: 184 µs
Wall time: 191 µs


tensor([ 4, 10, 18])

In [12]:
tensor_mul = torch.mul(tensor_a, tensor_b)
tensor_mul

tensor([ 4, 10, 18])

In [13]:
tensor_mul = tensor_a * 10
tensor_mul

tensor([10, 20, 30])

In [14]:
# Tensor Division
tensor_div = tensor_a / tensor_b
tensor_div


tensor([0.2500, 0.4000, 0.5000])

In [17]:
# Tensor Multiplication (Matric Multiplication)
tensor_mat_mul = torch.matmul(tensor_a, tensor_b)
tensor_mat_mul

tensor(32)

In [18]:
tensor_mat_mul = tensor_a @ tensor_b
tensor_mat_mul

tensor(32)

In [19]:
tensor_mat_mul = tensor_a.matmul(tensor_b)
tensor_mat_mul

tensor(32)

In [20]:
tensor_mat_mul = tensor_b.matmul(tensor_a)
tensor_mat_mul

tensor(32)

In [23]:
tensor_mat_mul = torch.matmul(tensor_a.T, tensor_b)
tensor_mat_mul

tensor(32)

#**Tensor Aggregation**

1. Min
2. Max
3. Mean
4. Sum etc.

In [27]:
tensor = torch.tensor([0,10,20,30,40,50,60,70,80,90,100])
tensor

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [37]:
# Find the min
torch.min(tensor), tensor.min()

(tensor(0.), tensor(0.))

In [38]:
# Find the max
torch.max(tensor), tensor.max()

(tensor(100.), tensor(100.))

In [39]:
# Find the mean
# remve the `type` and checj the error
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [42]:
# Find the Sum
torch.sum(tensor), tensor.sum()

(tensor(550.), tensor(550.))

In [44]:
#Find the index of the min and max elements
tensor.argmin(), tensor.argmax()

(tensor(0), tensor(10))